### ISSUE TITLE
Enums serialization

### ISSUE THREAD

**Issue by ertasso** [JodaOrg/joda-beans#112]
I cannot understand how Joda Beans serialize Enums.
Suppose I have defined this Enum:

	public enum MyEnum {
		A("stringA"),
		B("stringB");

		private String label;
	
		MyEnum(String label) {
			this.label = label;
		}
	
		@Override
		public String toString() {
			return label;
		}
	}

I expected to find "stringA" in the serialized Json string. Instead, it contains "A".
Is it possible to set Joda Beans in order to output the "label" field of my enum?

Thank you

**Comment by jodastephen** [comment]
Joda-Beans uses [Joda-Convert](http://www.joda.org/joda-convert) to serialize "simple" types, such as `Class`, `int` and enums. The mechanism for enums can be overridden using annotations - `@FromString` and `@ToString`. See [this enum](https://github.com/OpenGamma/Strata/blob/master/modules/finance/src/main/java/com/opengamma/strata/finance/rate/swap/CompoundingMethod.java#L62) for an example of what to do.
