### ISSUE TITLE
Basic documentation generator

### ISSUE THREAD

**Issue by ertasso** [JodaOrg/joda-beans#113]
Maybe it's just a weird idea, but: wouldn't it be nice to have a way to generate a "basic documentation" for all the Beans defined in a project?
With "basic documentation" I mean something like the definition of the bean, without all the methods build, get,... which appear in the Javadoc:

```
ImmutableBean A:
    string x (notNull)
    List<String> y (notEmpty)
```

I've just created a DataModel library for a new web app. I would like to give this basic documentation to the guys that will develop the JavaScript GUI.
I think that the complete JavaDoc could be too messy for them, since they are just interested in the content of the json string they will receive.

What do you think about it?
I've looked for a tool for doing this but I couldn't find it, so if it already exists... I apologize :)

Thank you

**Comment by jodastephen** [comment]
This is not a weird idea ;-) Although undoubtedly ever user would want their own documentation format. 

Ideally, I'd like to change Joda-Beans to allow other output files to be generated based on the internal code generation data model. One of these could be a documentation generator. The data model mostly exists in the code generator today, so in theory, it wouldn't be too hard a change.

An alternative approach would be to add a flag that causes the documentation to be added to the code generated section, then anyone could access it as a normal Java string.

The reality is that I don't have much time to do this, but it would allow lots of power.

For the basic documentation above, it only depends on the bean structure and content of the annotations. As such, you should be able to write it using the current generated meta-beans. The main thing you don't have access to is the documentation/Javadoc describing each property.

**Comment by jodastephen** [comment]
Closing this issue, as no plans to work on it. Anyone is free to use Joda-Bean meta-beans to generate whatever output they want.
