### ISSUE TITLE
Getting error "Unable to locate bean superclass" although everything is fine.

### ISSUE THREAD

**Issue by mediahype** [JodaOrg/joda-beans#116]
I am using eclipse with the joda beans maven plugin.

I was getting the error "Unable to locate bean superclass" and just could not explain why, because with another bean with exactly the same class hierarchy in place everything was working wonderfully.

I finally found out that the error occurs when writing:
`implements Bean{`

But is gone when writing
`implements Bean {`
(notice the extra space between "Bean" and the block delimiter)

It would be nice if you could fix this as it could frighten off newbies to your otherwise extraordinarily excellent lib.

**Comment by jodastephen** [comment]
Thanks for the issue. The Joda-Beans parser is not perfect (it is deliberately simple) but we should be able to fix this one.
