### ISSUE TITLE
AssertEquals with tolerance

### ISSUE THREAD

**Issue by ertasso** [JodaOrg/joda-beans#117]
Hi,
in order to junit-test, I would like to compare beans.
I'm using the BeanAssert.assertBeanEquals(Bean expected, Bean actual). It works fine (I love the detailed difference list) but I cannot use it because I get plenty of these errors:
"Content differs, expected Double <0.15> but was <0.15000000000000002>"

I can't avoid this because numbers are coming from a Math library which I don't control. 
For my tests, this difference is fine.
Is there a way to set a tolerance to use when comparing Doubles?

**Comment by jodastephen** [comment]
There is no current way to set such a tolerance, however it would probably be a good addition.
