### ISSUE TITLE
Use fields instead of getters for hashCode() and equals()

### ISSUE THREAD

**Issue by cjkent** [JodaOrg/joda-beans#118]
Generated `hashCode` and `equals` methods use getters to access the field values. I noticed this in an immutable bean with an array field where the getter clones the array to ensure immutability. This is obviously wasteful when the call site is inside the class and doesn't mutate the array.

At a minimum, the field should be used directly when it is cloned in the getter to improve efficiency. 

Arguably the fields should always be used directly as it is the contents of the fields that determine the state of the object, not necessarily the return value of the getters.

**Comment by jodastephen** [comment]
This can be done, but it could have hard to find incompatible effects on existing code. For example, where a getter does something clever, that is picked up by the equals/hashCode/toString at present. Given that this doesn't cause any real issues currently, I'm reluctant to change it.
