### ISSUE TITLE
ClassCastException when deserializing Double

### ISSUE THREAD

**Issue by ertasso** [JodaOrg/joda-beans#122]
Hi,
I have a problem with Double properties.

Suppose that I have a Bean with a Double property:

    @PropertyDefinition(validate = "Validator.notNull")
    private final Double value

When I try to deserialize this Json:
{"value": 100}
I get a `ClassCastException: java.lang.Integer cannot be cast to java.lang.Double`.

I searched through the code and I noted that every number which doesn't contain "E" or "." is considered as an Integer.
The same does not apply to the xml deserialization.

How can I solve the problem?
I would like not to change the property definition (from Double to Number).

Thank you!

**Comment by jodastephen** [comment]
I've added some leniency here.
