### ISSUE TITLE
How to wrap a map in a bean/ round trip?

### ISSUE THREAD

**Issue by puppetMaster3** [JodaOrg/joda-beans#124]
I have been kicking the tires on this project for a while.

This should be doable but I am wondering best way:
Make a Bean from Map?

{Also it be nice to go the other way.
Map m = toMap(Bean) 
}

Cheers

**Comment by jodastephen** [comment]
Take a look at `FlexiBean`. It may be what you want. You can use `FlexiBean.putAll(Map)` to set it up, and call `toMap()` to get the map back out.

**Comment by vicApakau** [comment]
That class is Final. I'm forced to wrap it.

**Comment by jodastephen** [comment]
`MapBean` ? Its a wrapper around an exposed `Map` that makes it into a `Bean`.

**Comment by puppetMaster3** [comment]
No Same one, FlexiBean that you told me to use. I wrapped it.

I have no idea what the diference is btwn MapBea and FlexiBean even after
reading the docs.

(also thx for all the code donated, including Time lib)

On Wed, Feb 3, 2016 at 3:47 AM, Stephen Colebourne <notifications@github.com

**Comment by jodastephen** [comment]
`MapBean` is the thinnest wrapper around a `Map` to make it into a `Bean`. It fully exposes the internal storage map. `FlexiBean` is more complex, hiding the internal map, but still allowing map-like operations.

Anyway, hope Joda-Beans work out for you.
