### ISSUE TITLE
Optionally disable generation of clone() method for Bean types

### ISSUE THREAD

**Issue by bcamel** [JodaOrg/joda-beans#135]
Apparently GWT 2.7.0 does not (easily) support `Object#clone()` [(see here)](https://code.google.com/archive/p/google-web-toolkit/issues/5068)

In `BeanGen.java` we can see that an override for `Object#clone()` will be omitted in the following cases

```
 private void generateClone() {
        if (data.isManualClone() || 
            data.isImmutable()   ||
            (data.isRootClass() == false && data.isConstructable() == false)) {
            return;
        }
...
```

These cases are obviously not feasible workarounds for the GWT issue (given we are implementing a `Bean` rather than an `ImmutableBean`).

Would it be undesirable to add a new attribute e.g. `cloneable` to the `BeanDefinition` annotation to optionally switch off the override of `clone()` ?

**Comment by jodastephen** [comment]
Providing the ability to control `clone` generation would be a suitable addition to Joda-Beans.

**Comment by bcamel** [comment]
I'll provide a PR soon then. Thank you.
