### ISSUE TITLE
Builder does not add items to lists

### ISSUE THREAD

**Issue by lourish** [JodaOrg/joda-beans#138]
If I have a bean class with a list, such as:

```
@BeanDefinition(builderScope = "public")
public class MyBean implements Bean {
    @PropertyDefinition
    private List<Object> myObjects;
```

When I use a builder to add list items the built bean has a null list. The test below fails as `myBean.getMyObjects()` is null.

```
    @Test
    public void canSetObjectsInList() {
        final MyBean myBean = MyBean.builder().myObjects(new Object(), new Object()).build();

        assertThat(myBean.getMyObjects()).hasSize(2);
    }

```

It appears from the MyBean generated constructor that it doesn't attempt to create a list:

```
    protected MyBean(MyBean.Builder builder) {
        if (myObjects != null) {
            this.myObjects.addAll(builder.myObjects);
        }
    }

```

Since the property `myObjects` in the constructor can only be null I can't see how this could ever work. 

If I were to create a list in the property definition then the creation works as long as I have list items in the builder, however it fails when there are no list items in the builder (i.e. when builder.myObjects is null).

Am I doing something wrong in the creation of my beans or is this a bug?

**Comment by jodastephen** [comment]
This seems to be a combination of options that has not been tested.

**Comment by lourish** [comment]
Thanks, can confirm it now works in 1.9.
