### ISSUE TITLE
Please add @Generated("joda-beans")

### ISSUE THREAD

**Issue by sdavids** [JodaOrg/joda-beans#149]
Generated/modified classes could be annotated with [@Generated](https://docs.oracle.com/javase/7/docs/api/javax/annotation/Generated.html).

Tools such as [errorprone](https://github.com/google/error-prone/issues/463) can be configured to ignore generated classes.

**Comment by jodastephen** [comment]
Noting that this is more complicated than it seems. The annotation will be changing package in Java 9. And with Joda-Beans, only part of the class is generated, important parts of user code are not generated, and users of error-prone would want those parts tested. As such, it seems to me that the annotation might well be a bad idea and hide certain errors.

Is there a specific case where the absence of the annotation has caused a real problem?

**Comment by sdavids** [comment]
Changing package?

http://download.java.net/java/jdk9/docs/api/javax/annotation/Generated.html

**Comment by jodastephen** [comment]
Basically, for Java 9 its in the "wrong" module, so they will add a new `@Generated`
http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-February/011365.html

**Comment by hackmann** [comment]
I think we could add it to the inner classes (Meta and Builder) and the toString, equals and hashCode methods.

**Comment by jodastephen** [comment]
And the new version  ended up in [javax.annotation.processing](http://download.java.net/java/jdk9/docs/api/javax/annotation/processing/package-summary.html) which is not good.

The only way I can do this is to add a command line flag (including to the maven plugin) to decide whether to generate the annotation and which version to use. This seems like a lot of effort...

**Comment by jodastephen** [comment]
Would https://github.com/JodaOrg/joda-beans/pull/209 satisfy the desire here?

**Comment by sdavids** [comment]
errorprone handles "javax.annotation.Generated" & "javax.annotation.processing.Generated":

https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/SuppressionInfo.java#L53

**Comment by jodastephen** [comment]
Thats fine, because the generated code doesn't insist on one or the other.

**Comment by jodastephen** [comment]
See #209
