### ISSUE TITLE
Improve builder implementations for subclasses

### ISSUE THREAD

**Issue by hackmann** [JodaOrg/joda-beans#153]
In version 1.10.1 the generated builder implementations for subclasses return the parent class' implementation when setting properties defined there. For example in TestSubBean instead of having one builder call chain like:
```
        ImmSubPersonNonFinal person= ImmSubPersonNonFinal.builder()
                .forename("John")
                .middleName("K.")
                .surname("Doe")
                .build();
```
This is split into three statements and the properties are reordered. First setting sub class properties and then parent class properties
```
        ImmSubPersonNonFinal.Builder builder = ImmSubPersonNonFinal.builder();
        builder
                .middleName("K.")
                .forename("John")
                .surname("Doe");
        ImmSubPersonNonFinal person = builder.build();
```

**Comment by jodastephen** [comment]
Because each bean is generated separately, there is no knowledge at present that can capture this.  Perhaps I can change an API as part of the Java 8 work to handle it better.
