### ISSUE TITLE
Suppress deprecation warnings in generated code due to deprecations in 1.11

### ISSUE THREAD

**Issue by sdavids** [JodaOrg/joda-beans#168]
_javac -Xlint_ shows deprecation warnings for every generated class.

Please change the generator to generate:

    @Override
    @SuppressWarnings("deprecation")
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

Same for _setAll()_ ...

**Comment by jodastephen** [comment]
How about this?

    /**
     * {@inheritDoc}
     * @deprecated Use Joda-Convert in calling code
     */
    @Override
    @Deprecated
    public Builder setString(String propertyName, String value) {
        setString(meta().metaProperty(propertyName), value);
        return this;
    }

or 

    @Override
    @Deprecated
    public Builder setString(String propertyName, String value) {
        setString(meta().metaProperty(propertyName), value);
        return this;
    }

Trying to keep checkstyle happy as well. I've not used javac lint myself.

**Comment by jodastephen** [comment]
This satisfies things AFAICT:

    /**
     * @deprecated Use Joda-Convert in calling code
     */
    @Override
    @Deprecated
    public Builder setString(String propertyName, String value) {
        setString(meta().metaProperty(propertyName), value);
        return this;
    }
