### ISSUE TITLE
How to treat beans split up into interface and implementation

### ISSUE THREAD

**Issue by hoijui** [JodaOrg/joda-beans#181]
So i have two OSGi bundles, one with interfaces, one with implementations.
Lets say, i have `public interface Person` in one bundle, and `public class PersonImpl implements Person` in th other.
I would like to generate getters, setters and `addPropertyChangeListener()` in the interface, and the implementations of those in the class.
Is this possible with JodaBeans, and if so, how?
If not, can you recommend some other library or tool that can do this?
...or am i not seeing some fundamental problem about this idea here?

**Comment by jodastephen** [comment]
This is not possible with Joda-Beans. It would take a lot of work to add such a separation, and I'm not likely to do it. The [Immutables project](https://immutables.github.io/) may be what you want.

**Comment by hoijui** [comment]
ahh perfect, thanks you stephen! :-)
in the meantime, i have decided to learn scala instead. i am not sure if it solves my problem well, but so far it looks good, and it seems like a language i really would like to get to know anyway.

**Comment by jodastephen** [comment]
My views on Scala are [well known](http://blog.joda.org/2011/11/scala-feels-like-ejb-2-and-other.html), if you are looking for an alternative language, Kotlin is a far better choice.

**Comment by hoijui** [comment]
reading some of your blog, i see that you are (were?) also a fan of
fantom. would you nw recommend kotil over fanto? mostly because it has
more support/community/market-share?

2018-01-09 18:19 GMT+01:00, Stephen Colebourne <notifications@github.com>:

**Comment by jodastephen** [comment]
Fantom is very interesting due to its weak type system. Kotlin is likely to be a relatively major language due to the Android ecosystem, so is a much better choice to learn for practical industry usage as of now.

**Comment by hoijui** [comment]
cool. thanks! :-)
iam trying out kotlin now

2018-01-12 15:54 GMT+01:00, Stephen Colebourne <notifications@github.com>:
