### ISSUE TITLE
invalid generated code because of extra space in variable declaration 

### ISSUE THREAD

**Issue by akaigoro** [JodaOrg/joda-beans#182]
Following declaration:

    @PropertyDefinition
    private String  notes; // 2 space characters

results in:

    public  getNotes() {
        return notes;
    }

    public void setNotes( notes) {
        this.notes = notes;
    }

That is, class identifier is missing in setters and getters.

**Comment by jodastephen** [comment]
The general rule is that you are supposed to format your code correctly, as the Joda-Beans parser is not intended to be as complete as that of the JDK. However, in this case I would have thought the Joda-Beans parser could catch the issue.

**Comment by akaigoro** [comment]
What is incorrect in having 2 spaces instead of 1? What rule is violated?
