### ISSUE TITLE
Joda-beans 2.1 not compatible with OW2 ASM 5.0

### ISSUE THREAD

**Issue by imode69** [JodaOrg/joda-beans#188]
Not certain but is seems that joda-beans 2.1 (or one of it's transitive dependencies) on the maven repo was compiled with Java 9. This is causing an issue running a web service in TomEE 8.5 given that there is a dependency in tomcat on the ASM 5.0 bytecode manipulation library which only supports <= Java8.

**Comment by jodastephen** [comment]
Joda-Beans code is still based on Java 8, but the jar file contains `module-info.class` compiled on Java 9. That is how the project is built now, so if you can't work with it you'd need to remove `module-info.class` from the jar file.

**Comment by imode69** [comment]
Hi,

I need the streaming bug fix in 2.1 but my (arcane) company policy prevents me from modifying 3rd party jars. I could possible get around it be compiling the source and installing the resultant jar in our local repo. I think the J9 dependency in 2.1 is going to break various byte-code analyzers. Would it be possible to create and upload to maven a J8 only 2.0.3 version with the fixes?

-thanks
Richard

**Comment by jodastephen** [comment]
I'm sorry, but forking the project for company policies or outdated app servers isn't really practical. Java 11 will be out in 7 months time and is the next long term support release, with Java 8 support stopping soon after. Also, bear in mind that more and more libraries are going to contain `module.info.class` going forward - this problem isn't going away!

**Comment by jodastephen** [comment]
For v2.2 there is a "classic" version of the jar file:

```
<dependency>
  <groupId>org.joda</groupId>
  <artifactId>joda-beans</artifactId>
  <version>2.2</version>
  <classifier>classic</classifier>
</dependency>
```

**Comment by bjhargrave** [comment]
I wonder if putting `module-info.class` in `META-INF/versions/9` (and adding `Multi-Release: true` to the manifest) could avoid the need for a classic variant?

**Comment by jodastephen** [comment]
No, as some tools can't cope with multi-release jars.

**Comment by bjhargrave** [comment]
Caught between a rock and a hard place... :-)
