### ISSUE TITLE
Null Double parsed as NaN

### ISSUE THREAD

**Issue by ertasso** [JodaOrg/joda-beans#192]
I think there is some ambiguity in how the null numeric values are parsed. Or, at least, it would be nice to have a somehow configurable behaviour.

Here is the issue.
I have this bean:
```
@PropertyDefinition(validate = "notNull")
private final Double number;
```
When I parse the following jsons (which should represent the same content) I get two different results
```
{"number":null} --> number=Double.NaN
{} --> number=null --> IllegalArgumentException("Argument number must not be null")
```

I expected to get the exception in both cases.
What do you think?

I noticed that AbstractJsonReader leniently accepts null as NaN. Would it be possible to change this in your opinion?

**Comment by jodastephen** [comment]
The normal way to write a primitive value is:

    @PropertyDefinition
    private final double number;

JSON [does not support](https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript) NaN, so the parsing of `null` is intended to provide a backdoor way of passing NaN from something that strictly rejects NaN.

I'd be reluctant to change the behaviour as someone may be relying on it.

**Comment by jodastephen** [comment]
The linked PR does not directly address this issue, but it does allow control over NaN output and extends output/input to support JSON5 literals.
