### ISSUE TITLE
code generation: redundant "implements Bean" in subclass leads to incorrect Meta class declaration

### ISSUE THREAD

**Issue by bobtins** [JodaOrg/joda-beans#194]
I'm using joda-beans 2.3 and the maven plugin 1.1. I can work up a full Maven project containing the test case if needed.

I was stumped by this issue until I narrowed it down to a simple example with two bean classes, one a subclass of the other:
### Base.java
```java
import org.joda.beans.Bean;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;

@BeanDefinition
public class Base implements Bean {
    
    @PropertyDefinition
    private String foo;
    
}
```

### Derived.java
```java
import org.joda.beans.Bean;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;

@BeanDefinition
public class Derived extends Base implements Bean {

    @PropertyDefinition
    private String bar;
}
```

After running `mvn joda-beans:generate`, the generated meta() method has the compilation error `The return type is incompatible with Base.meta()`. The same error also occurs with the metaBean() method.

I found that this was due to the Meta class declaration in Derived.java:
```java
    public static class Meta extends DirectMetaBean {
```
If I remove the redundant "implements Bean" from the Derived class declaration and regenerate the code, the Derived.Meta declaration changes to this:
```java
    public static class Meta extends Base.Meta {
```
and the resulting code has no errors.

**Comment by jodastephen** [comment]
This is behaving as expected. Each file is processed completely separately, and the parser has no understanding of the meaning of the class `Base` when it processes `Derived`. As such, there is no way of knowing whether `extends Base` means that the class is extending a bean or a non-bean. However, when it sees `implements Bean` it assumes that this is the root of the hierarchy and behaves as such. Sadly in your case, that means you get an error, sorry.

**Comment by bobtins** [comment]
OK, thanks for clearing that up. I remember reading the section about the limitations of the parser, and I went back to reread it. You state up front that the parser is "deliberately simplistic", but I suppose that I was lulled into thinking that it had compiler-level knowledge because it appeared to be doing pretty intelligent things. I guess this is my own brain doing "duck typing".

I accept the limitations of the parser--I'm assuming that for the tool to know about type relationships, you'd have to rewrite it and make it a lot more complex.
