### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by martynassateika** [JodaOrg/joda-beans#198]
Hey Stephen,

I was looking through the JodaBean docs and noticed a broken link in https://www.joda.org/joda-beans/userguide-codegen.html

In the docs of `PropertyDefinition#set` there's a link that points to https://www.joda.org/joda-beans/apidocs/org/joda/beans/PropertyDefinition.html#set-- which is invalid.

**Comment by martynassateika** [comment]
Thanks, noticed this was fixed in 54371529cc78c219dc4dda77ac6d424b8608cb72.

**Comment by jodastephen** [comment]
Thanks for letting me know
