### ISSUE TITLE
Bean with no properties missing builder ctor, subclass doesn't compile

### ISSUE THREAD

**Issue by bobtins** [JodaOrg/joda-beans#200]
I'm creating a bean hierarchy with _builderScope = "public"_, and I have an abstract base bean class with no properties, in order to provide some housekeeping functions. The generated builder only has a single no-arg constructor. When I subclass this bean, the generated builder for the subclass has both a no-arg and a one-arg builder. The one-arg builder will call the superclass one-arg builder which doesn't exist, resulting in a compile error:
```
[INFO] Compiling 2 source files to F:\projects\git-jrs\jrs-server\jbtest\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \projects\git-jrs\jrs-server\jbtest\src\test\java\jodabeanstest\DerivedBean.java:[229,12] error: constructor Builder in class Builder cannot be applied to given types;
```
See attached zip for test case.
[joda-beans-missing-ctor.zip](https://github.com/JodaOrg/joda-beans/files/2814914/joda-beans-missing-ctor.zip)

**Comment by bobtins** [comment]
Would it be sufficient to take out the "if" test in generateBuilderConstructorCopy()?https://github.com/JodaOrg/joda-beans/blob/b271a8916c21f1ba7a6629a1e583b98723d3a604/src/main/java/org/joda/beans/gen/BeanGen.java#L1276

**Comment by jodastephen** [comment]
Can you test the branch? I'd like to know if it fixes your use case. Thanks
