### ISSUE TITLE
Support one-line property definitions

### ISSUE THREAD

**Issue by mwkroening** [JodaOrg/joda-beans#202]
Currently one-line property definitions are not supported:
```java
@PropertyDefinition private String forename;
```
has to be changed to:
```java
@PropertyDefinition
private String forename;
```

It would be great, if one-line property definitions would be supported, because that's the way [google/google-java-format](https://github.com/google/google-java-format) formats simple fields.

**Comment by mwkroening** [comment]
All right. I just wanted to experiment with my current project and saw this problem occur.

To be honest, if it would be quite tricky to achieve this, it might not be worth it. But perhaps one day, I'll come back to this.

**Comment by jodastephen** [comment]
Closing for now. Feel free to reopen in the future if necessary.
