### ISSUE TITLE
JodaBeanTests.coverMutableBean fails if derived bean has no Joda properties

### ISSUE THREAD

**Issue by schubertf** [JodaOrg/joda-beans#210]
I have a base bean and a derived bean, but the derived bean has no Joda properties.
i.e. the derived bean has no properties that are annotated with PropertyDefinition.
This is because I have no properties in the derived bean that I want to serialise in/out, or because they are for internal use only.
If I then write a Junit test for the derived bean and try to get my code coverage up by using JodaBeanTests.coverMutableBean, the test fails.

See attached zip.
In this case, if you run mvn test, it will fail with...
java.util.NoSuchElementException: Unknown property: baseBeanProp
        at jodabeanstest.DerivedBeanTest.testCoverBean(DerivedBeanTest.java:23)

[jodabeans.coverMutableBeanFails.IfDerivedBeanHasNoJodaProperties.zip](https://github.com/JodaOrg/joda-beans/files/3291238/jodabeans.coverMutableBeanFails.IfDerivedBeanHasNoJodaProperties.zip)

**Comment by jodastephen** [comment]
Fixed thanks
