### ISSUE TITLE
Unable to locate bean superclass

### ISSUE THREAD

**Issue by nhojpatrick** [JodaOrg/joda-beans#211]
Currently using joda-beans v2.2.1 and joda-beans-maven-plugin v1.1. Trying to upgrade but have issue with the parser. "Error while running Joda-Beans tool: Unable to locate bean superclass: Error in bean path, Line x"

```
package

import 1;

/**
 * ...
 */
@BeanDefinition
@Entity
@Table(...)
@NamedQueries({
   ...
})
public class MyObject
        implements Bean,
        CustomInterface,
        Serializable {
...
}
```

I think I've tracked the issue to the @BeanDefinition placement from v2.2.1 to v2.2.2 change so it needs to be the last annotation before `public class`. But I've got some that work without moving the annotation but the ones that fail if i move it to the last annotation then pass.

**Comment by jodastephen** [comment]
The change allows a line that starts with '@' and ends with '{' to *not* be identified as the end of the class header. It won't handle all cases, but will handle the one above.
