### ISSUE TITLE
Checkstyle OFF/ON block comments

### ISSUE THREAD

**Issue by nhojpatrick** [JodaOrg/joda-beans#214]
I have a projects with 50 JPA objects, but they produce about ~40,000 Checkstyle warnings, with ~39,950 are within the AUTOGENERATED section. So 50 are in code I author.

Working on PR to add `//CHECKSTYLE:OFF` and `//CHECKSTYLE:ON` within the auto generated section. Associated PR will be raised shortly for early early review.

**Comment by jodastephen** [comment]
Checkstyle has the ability to customize the on/off text it looks for. Can you use that customization?

**Comment by jodastephen** [comment]
Here is the [config](https://checkstyle.sourceforge.io/config_filters.html#SuppressionCommentFilter) that should do the job.

    <module name="SuppressionCommentFilter">
      <property name="offCommentFormat" value="AUTOGENERATED START"/>
      <property name="onCommentFormat" value="AUTOGENERATED END"/>
    </module>

**Comment by jodastephen** [comment]
Closing on the assumption that the config worked.
