### ISSUE TITLE
Line separator command line argument for BeanCodeGen

### ISSUE THREAD

**Issue by biteytech** [JodaOrg/joda-beans#228]
I do most of my coding on Windows, but my team has standardized on LF instead of CRLF. I realize that git has the ability to convert line separators, but I would prefer to write the generated files with LF directly. This appears to be a simple change as it only affects writing the file contents (does not affect parsing).

[joda-beans pull request](https://github.com/JodaOrg/joda-beans/pull/227)
[jodaorg.github.io pull request](https://github.com/JodaOrg/jodaorg.github.io/pull/7)
[joda-beans-maven-plugin](https://github.com/JodaOrg/joda-beans-maven-plugin/pull/14)

**Comment by jodastephen** [comment]
Done thanks
