### ISSUE TITLE
Documentation should mention that classes need to be final to generate a public constructor with all fields

### ISSUE THREAD

**Issue by mikeyg123** [JodaOrg/joda-beans#285]
These 2 classes generate different constructors:

```
@BeanDefinition(constructorScope = "public")
public class Item implements ImmutableBean {
    @PropertyDefinition
    private final String name;
}
```

```
@BeanDefinition(constructorScope = "public")
public final class Item implements ImmutableBean {
    @PropertyDefinition
    private final String name;
}
```

Expected that they would both cause the generation of a public constructor with all the fields as parameters. But the non-final class generates a constructor that takes the builder as parameter.

This behaviour should be changed so the non-final class also generates a constructor with all fields, or the behaviour should be mentioned in the user guide under "Immutable Bean Customisation" https://www.joda.org/joda-beans/userguide-codegen.html .

**Comment by jodastephen** [comment]
Do you need the builder? If not you can achieve what you want by adding `style = "light"`

Either way, this would be a reasonable additional setting.

**Comment by mikeyg123** [comment]
Other code is using the builders unfortunately.  I need a single constructor that takes field values for deserialisation from bson within spring-data-mongodb. 
I'm manually adding a constructor where classes can't be final (annotated with @PersistenceCreator where it is not the only constructor)
