### ISSUE TITLE
Observable property - feature request

### ISSUE THREAD

**Issue by jvmlet** [JodaOrg/joda-beans#78]
Hi
Would you please add "Observable property" feature by  invoking firePropertyChange in generated setter  method?
This also requires to generate addPropertyChangeListener  and removePropertyChangeListener methods ,plus PropertyChangeSupport field.

This could be controlled by extending @PropertyDefinition with "observable=true"  attribute.

Thanks
Alexander

**Comment by reggiepierce** [comment]
Hi All,

I'd like to second this request for use in Vaadin. I'd be glad to help any way I can. I'm assuming that it could be done via something in the generated setter,  and perhaps defined with an annotation?

```java

    @PropertyDefinition(validate = "notEmpty", notifyOnSet=true)
    private String userId;

public void setUserId(String userId) {
        JodaBeanUtils.notEmpty(userId, "userId");
        this.userId = userId;
        //this would have to be generated
        propertySetChange("userId");
    }
'''

**Comment by jodastephen** [comment]
Basic support for bound properties added, intended for simple mutable properties only:

    @PropertyDefinition(set = "bound")

The `PropertyChangeSupport` field is generated, but not the add/remove listener methods.
